### ISSUE TITLE
MVP of hxl-proxy

### ISSUE THREAD

**Issue by fititnt** [covid-taskforce-cplp/hxl-standard-tools-stack#2]
> From https://github.com/covid-taskforce-cplp/hxldash-docker/issues/4

Related:
- Public proxy: https://proxy.hxlstandard.org/
- Docker image: https://hub.docker.com/r/unocha/hxl-proxy
- GitHub source: https://www.github.com/HXLStandard/hxl-proxy

**Comment by fititnt** [comment]
Still working on the Traefik 2.2 default configuration, but this already is an draft. 


### docker/full-stack/docker-compose.yml
```yaml
version: "3"

services:

# (...)

  hxl-proxy:
    image: unocha/hxl-proxy:1.18 # see https://hub.docker.com/r/unocha/hxl-proxy/tags
    # command: python manage.py runserver 0.0.0.0:8000
    # depends_on:
    #   - postgres_hxl-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hxl-proxy.rule=Host(`proxy.hxl.etica.dev`)"
      - "traefik.http.routers.hxl-proxy.entrypoints=web,websecure"
      - "traefik.http.routers.hxl-proxy.tls.certresolver=letsencrypt"
```

Preview of the load balancer dashboard. Very different from the Traefik 1.x version.


![Captura de tela de 2020-04-07 02-06-40](https://user-images.githubusercontent.com/812299/78632105-84562900-7874-11ea-8c43-0c9153dac8c2.png)
